// styles
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import '@/styles/globals.css'
// next
import type {AppProps} from 'next/app'
import ResponsiveAppBar from '@/components/layout/navbar'
import Head from 'next/head'
// mui
import Container from '@mui/material/Container'

export default function App({Component, pageProps}: AppProps) {
  return (
    <>
      <Head>
        <title>TCM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <Container maxWidth="xl" sx={{flexGrow: 1, my: 3, mx: 2}}>
        <Component {...pageProps} />
      </Container>
    </>
  )
}
